### ISSUE TITLE
Lagmonitor uses "Unknown Player" instead of name

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K#1815]
Since approximately the latest extended stable, the game generates resign messages that are inaccurate:

- "Player X has resigned and is now spectating" while the player was a spectator to begin with.
- "Giving all units of Player X to Player Y due to lag/AFK" while Y is on an enemy allyTeam of X.

**Comment by Anarchid** [comment]
Probably fixed by 8043568fba8f406926738bdab4c6220673f9f07f

**Comment by Anarchid** [comment]
Apparently still happens.

**Comment by ArchShaman** [comment]
I've noticed a lot of Unknown Player stuff today. Probably should check out lagmonitor.

**Comment by sprunk** [comment]
Still happens?

**Comment by GoogleFrog** [comment]
The fake news is gone now that playerIDs are used in GetPlayerInfo and teamIDs are used in GetTeamInfo (not the other way around). However there is still an issue with "Unknown Player" popping up more than it should. This occurs when a team is killed and the players are booted from the team into being spectators. The gadget doesn't know the name to give the team in this case. It needs some memory as a fallback.
