### ISSUE TITLE
campaign: playing coop erases personal progress

### ISSUE THREAD

**Issue by Xollir** [ZeroK-RTS/Zero-K#3030]
I had played the campaign solo. After playing the campaign coop with a friend, my progress seems to have been reset to his. He started the missions. If it helps, the "saves/campaign" folder contains only one file called "saveFile1.lua". The field commanderName in that file is set to my friend's id.

**Comment by GoogleFrog** [comment]
When was this? I fixed this and then was unable to reproduce any issues a day ago.

**Comment by Xollir** [comment]
The coop games were a few days ago. I only noticed my progress was missing today. So it is probably the issue you already fixed. I will report in case it happens again.

**Comment by GoogleFrog** [comment]
Thanks and sorry about that, reopen if it does.

**Comment by Cat-Lady** [comment]
Can we reopen this? It still happens - albeit the progress isn't truly lost. the thing is that sometimes (not 100% reproducibly), under:

`Zero-K/Saves/campaign/`

...new file - named "saveFileX.lua" ("X" being number - 2, 3, 4, etc...) is created, in addition to regular saveFile1.lua that is present there, and contains player's progress.

For some reason, it is the "higher" named file that is picked up by chobby as player campaing to show (it contains progress and commander - including name - of the player that was hosting co-op). If the surplus file gets removed, the "true" local player progress returns to chobby.

**Comment by Cat-Lady** [comment]
Well, it turns out that the file doesn't even need to be deleted - you can get inco campaing -> options button (people, including me, mistake it for going it regular options - maybe it should be called "campaing settings"?), and select campaing progress file to use.

The issue seems to be that game default to highest named/most recently added file (aka, the one from co-op), instead to sticking to whatever was set by user, until user manually swaps campaings to use.

**Comment by GoogleFrog** [comment]
I'm not reopening this in this repository. Use this https://github.com/ZeroK-RTS/Chobby/issues

It is also not reopening it because reopening related tickets from a year ago is just not how to use ticket systems. Make a new ticket and link to the old one if you want to. This sets you up as the user with the issue, with the rest of the comments talking about **that exact issue.** Attempts to hijack solved issues is annoying, especially because I can clearly see that your issues are distinct. Don't feel like you need to cut down on ticket spam.
