### ISSUE TITLE
White Map on the Third Campaign Map

### ISSUE THREAD

**Issue by brandonegbert** [ZeroK-RTS/Zero-K#5333]
When I play on the third campaign mission, the entire map is flat white.   The first two missions were fine.  I tried futzing with various graphics settings and none of them seemed to make a difference.  See: https://steamcommunity.com/sharedfiles/filedetails/?id=3298955235

Here's the infologs:
[infolog.txt](https://github.com/user-attachments/files/16407908/infolog.txt)
[infolog_full.txt](https://github.com/user-attachments/files/16407911/infolog_full.txt)

Logs have several references to my system not supporting shaders (which is not correct). 

Here's my steam system information:

Computer Information:
Manufacturer: Micro-Star International Co., Ltd.
Model: PRO B650M-A WIFI (MS-7D77)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 9 7950X 16-Core Processor
CPU Family: 0x19
CPU Model: 0x61
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 5881 MHz
32 logical processors
16 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Supported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Supported
AVX512VNNI: Supported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Arch Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.10.1-zen1-1-zen
X Server Vendor: The X.Org Foundation
X Server Release: 12401001
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20240610.91380
Video Card:
Driver: AMD AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 18.1.8, DRM 3.57, 6.10.1-zen1-1-zen)
Driver Version: 4.6 (Compatibility Profile) Mesa 24.1.4-arch1.2
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x1002
DeviceID: 0x73bf
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23.50" x 13.23" (26.97" diag), 59.7cm x 33.6cm (68.5cm diag)
Primary VRAM: 16384 MB
Sound card:
Audio device: ATI R6xx HDMI
Memory:
RAM: 64039 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 1903120 MB
Largest Free Hard Disk Block: 154397 MB
Storage:
Number of SSDs: 1
SSD sizes: 0B
Number of HDDs: 0
Number of removable drives: 0

**Comment by GoogleFrog** [comment]
First thing I'd try is typing /advmapshading. Press F8 and you should see a recognition of the toggle in the console.

**Comment by brandonegbert** [comment]
map shaders enabled: https://steamcommunity.com/sharedfiles/filedetails/?id=3304928410
map shaders disabled: https://steamcommunity.com/sharedfiles/filedetails/?id=3304927923

Slightly different.  Also, apparently units have decided to render this week when they weren't last week.

**Comment by alexpyattaev** [comment]
Same issue on my machine. 
Mesa version 24.1.5-1  
GPU: VGA compatible controller: Intel Corporation Raptor Lake-P [UHD Graphics] (rev 04)
No alarming messages in infolog...

**Comment by GoogleFrog** [comment]
1-2 frames of working before the map turns white is interesting. Can you try fiddling with fog start and fog end in the ingame (F10) menu?
![image](https://github.com/user-attachments/assets/d7de2d79-793a-4f80-a3c9-3b2ccfbf0693)

Fog is meant to not exist at all, but the way we are disabling it might have broken something.

Perhaps also mess with sun. And try typing '/luaui disable' to remove the UI (it can be reenabled with '/luaui reload').

**Comment by alexpyattaev** [comment]
Hey that worked! In the screenshot you can see the settings that make the map visible again. 

![image](https://github.com/user-attachments/assets/b723131f-cb60-46d6-a9de-09580cf16225)

**Comment by alexpyattaev** [comment]
And very similar issue with mechadansonia, moving both sliders all the way to the right makes the map work again.
![image](https://github.com/user-attachments/assets/78017ea3-124a-42c6-a29d-5ac3a3709290)
Interestingly, it seems these got moved while map was loading (or maybe they do not persist across battles). Either way, the fix was the same.
The other difference is that on mechadansonia there were no correctly rendered frames before whole thing turned white-out for me.

PS: The entire fog menu is kinda cryptic, I'd expect these to be map settings, not game settings, do you know what is up with all that? As in, how is that intended to work?

**Comment by GoogleFrog** [comment]
@alexpyattaev or @brandonegbert can you test that fix and report back? Then I'll make a stable for it.

To test open a multiplayer game, set to Custom and with a password. Then do '!game zk:test'.

> PS: The entire fog menu is kinda cryptic, I'd expect these to be map settings, not game settings, do you know what is up with all that? As in, how is that intended to work?

The sun, fog and water menus are for configuring maps then saving the overrides, per map. I've fixed the overrides for the maps.

**Comment by alexpyattaev** [comment]
Both maps appear fine on the test version, thanks! The non-test version is still broken, so it must be that the fix is working as intended.

**Comment by brandonegbert** [comment]
>To test open a multiplayer game, set to Custom and with a password. Then do '!game zk:test'.

I didn't even have to do this and the 3rd campaign map now works.  Guessing you pushed an update?

**Comment by sprunk** [comment]
Yes, there was an update today. Looks like 8d0a549b59b8ad3a71b9d072ea94f7a60805fe36 fixed it.
